Capstone project 1
blase147/alumni-club pull request #1
Opened 2022-09-23 05:59 UTC by blase147

In this project, I built a landing page for an Alumni Association as well an About page.
I also added a dynamic display using javascript to featured speakers. s an added feature, I created a contact form with form validation.
In addition, I made both mobile version and desktop versions of the project while using Lato font(typography)

2022-09-23 06:40 UTC, levy002 requested changes
hello @blase147 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that fails linters check. KIndly fix that.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-23 10:33 UTC, awais-amjed requested changes
# STATUS: CHANGES REQUIRED ♻️

Hi @blase147 , 

Good job so far! 👏👏
There are some issues that you still need to work on to go to the next project but you are almost there! 🥳🙌🤗

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)

## Required Changes ♻️

- [ ] Kindly add a demo video for your Project to the description of the PR as described in the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md#project-documentation) 🤗
![image](https://user-images.githubusercontent.com/73714615/191938087-67e7fb91-51fe-4eb6-aa0f-c9dd81824216.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 10:33 UTC, awais-amjed commented on README.md
Kindly replace your Readme file with [Microverse Readme Template](https://github.com/microverseinc/readme-template) and customize it according to your Project 🤗

Also, please make sure that your README contains an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-09-23 10:33 UTC, awais-amjed commented on index.html
> +  <link rel="stylesheet" href="/style/DesktopIndex.css">
Kindly note that using absolute path doesn't work on GitHub Pages, this is the reason your styles are not being loaded in the live version. Kindly replace it with a relative path - that should fix the problem 😃
```href="./style/mobileIndex.css"```

![image](https://user-images.githubusercontent.com/73714615/191939651-cd191a14-a929-4c9a-bf4a-8c598a472e06.png)

2022-09-23 10:33 UTC, awais-amjed commented on index.html
> +        <a href="https://twitter.com/ChukwumaMosanya"><i class="fa-solid fa-twitter twitter-icon"></i></a>
Kindly fix these icons, they are not being displayed in the Webpage 🤗

![image](https://user-images.githubusercontent.com/73714615/191940146-9b107871-3b19-4055-a6a7-b654cc22f5be.png)

2022-09-23 10:33 UTC, awais-amjed commented on index.html
> +        </div>
Kindly fix the styling of these navigation links to resemble the given design 🤗

Your design:

![image](https://user-images.githubusercontent.com/73714615/191940443-c8a62338-03b8-40df-a9a7-c8f7a6b554e1.png)

Template design: 

![image](https://user-images.githubusercontent.com/73714615/191940411-de702073-ad53-49c3-ab9c-ee6dcef1e9aa.png)

2022-09-23 10:33 UTC, awais-amjed commented on pages/about.html
> +            </div>
Kindly apply the changes requested above to the navbar in about page as well, and try to make the design resemble the given template 🤗

![image](https://user-images.githubusercontent.com/73714615/191941298-cde1f720-1c7f-4057-bbfe-3ee5aff34046.png)

2022-09-23 10:33 UTC, awais-amjed commented on pages/about.html
> +            </form>
[OPTIONAL] It's better to remove this form since this is not the part of design 🤗

2022-09-23 10:33 UTC, awais-amjed commented on index.html
> +<section class="desktop-footer">
Kindly replace this `section` tag with `footer` tag since this block is the footer of your page 🤗

2022-09-23 10:33 UTC, awais-amjed commented on pages/about.html
> +                    </div>
Kindly replace this `div` tag with `footer` tag since this block is the footer of your page 🤗

2022-09-23 10:33 UTC, awais-amjed commented on index.html
> +      <h1>Featured Speakers</h1>
Kindly replace this `h1` tag with `h2` since there should only be one `h1` tag per page following the best practices 🤗

2022-09-23 17:10 UTC, BertrandConxy requested changes
Hi @blase147 ✋, 

Great work on making the changes requested by a previous reviewer 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Highlights 💪 

- No linter errors
- correct flow is used
- good improvement based on the previous reviewer's suggestions
- good PR

 ## Required Changes ♻️

- [ ] Great improvement so far 👏. As the previous review suggested, please record a video presenting your project and then, share the link in your Pull request summary. The video presentation is important as it showcases your ability to present your work to the world 😎. Please head back to the following project requirements [here](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md#project-documentation:~:text=Project%20documentation,pull%20request%20description.) for more information 🏃 
- [ ] Now due to different changes you have been making while I was reviewing your codes, I found out that at some time, you ended up breaking the stylesheet link in the index.html again as before the first review. But what I can is that before I start reviewing it, the live demo was having the style, it only broke after some changes you introduced. Please fix it 😉 
![image](https://user-images.githubusercontent.com/90222110/192015464-eae78019-b6fa-4700-9978-88efefb8eb20.png)


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 17:10 UTC, BertrandConxy commented on index.html
> +
- [ ] As suggested by the previous reviewer, please adjust your navigation bar (including nav links styles) in order to match the design given. From the comparison, you can observe that there are still a lot to be improved.
**Given design**
![image](https://user-images.githubusercontent.com/90222110/192009802-3eb0c2f7-b52d-4010-984b-648a73311ac5.png)

**Your design**
![image](https://user-images.githubusercontent.com/90222110/192009919-64e3da0c-9dab-4ae9-9890-cc8b0c863fb7.png)

- Starting with the font color of the nav links, please change it to `dark-grey color`
- the CC Campain link is in `orange` color
- the Nav bar has the box shadow at the bottom
- Please reduce the space between nav links

2022-09-23 17:10 UTC, BertrandConxy commented on pages/about.html
> +
- [ ] As suggested by the previous reviewer, please apply the same style changes to the `about page` nav bar because it should look the same as the one on the home page 😃 👍 

![image](https://user-images.githubusercontent.com/90222110/192011000-6438efe7-fc7b-4aab-a2bd-6ee090fc5880.png)

2022-09-23 17:10 UTC, BertrandConxy commented on pages/about.html
> +                      <img src="../images/mozilla.jpeg" alt="Partner">
- [ ] [OPTIONAL] As it is stated in the HTML&CSS best practices, please use the correct indentation in all your HTML codes. VS code extensions like `prettier` can organize the codes for you so that you can focus more on writing the codes 😉

2022-09-23 17:10 UTC, BertrandConxy commented on index.html
> +    <div class="main-description-container">
- [ ] From the design guidelines, this text should be very big compared to others so as to stand out and capture visitors' focus very quickly. I would suggest you styles it the same way on your website 😉
**Design given**
![image](https://user-images.githubusercontent.com/90222110/192012532-b3dbc5ca-d7e6-4844-87ba-cc6423a40ed1.png)
**Your design**
![image](https://user-images.githubusercontent.com/90222110/192012598-77d5d044-6bd1-4a3a-b698-a9b54d5ca987.png)

2022-09-23 17:10 UTC, BertrandConxy commented on index.html
> +          </p>
- [ ] Please give each of your program card heading the `orange color` so that they can look the same as the design given 👍 
**Your design**
![image](https://user-images.githubusercontent.com/90222110/192013042-a25167cc-19fd-45bb-b2dd-6e2d466dc7bb.png)
**Given design**
![image](https://user-images.githubusercontent.com/90222110/192013123-15375620-bfd2-48d7-bb6d-0f7e8f5f8fa7.png)

2022-09-23 17:10 UTC, BertrandConxy commented on style/DesktopIndex.css
> +  }
- [ ] Please add the correct background color which matches or looks almost like the design given. If you can't find the background image that looks great, I would suggest you use the `light-grey` background color
**Your design**
![image](https://user-images.githubusercontent.com/90222110/192013625-ce962248-d236-4247-9eda-2fb4a60adace.png)

Given design
![image](https://user-images.githubusercontent.com/90222110/192013690-b299af28-364b-40ec-b738-a911d009217d.png)

2022-09-23 17:10 UTC, BertrandConxy commented on index.html
> +</div>
- [ ] The images in the featured speakers' sections look broken. please fix them up 👇 
![image](https://user-images.githubusercontent.com/90222110/192014098-f608a4ec-3fc4-4509-b708-20335040ec7f.png)

2022-09-23 17:10 UTC, BertrandConxy commented on pages/about.html
> +          <i class="fas fa-bars"></i>
- [ ] The hamburger menu on the about page is not working. please fix it up 🏃

2022-09-24 12:39 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @blase147  

Your project is complete! Great job for making the requested changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Validations correctly implemented
- design well followed
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 12:39 UTC, tufoinnkuo10 commented on js/index.js
> +const menuBtn = document.getElementById('menu-btn');
- [ optional] great job with the mobile menu. please ensure that when it pops up, the user should use only it to navigate or close it before continuing/been able to scroll through your page/site

![Screenshot (467)](https://user-images.githubusercontent.com/65298048/192098349-2acbe15e-6eb4-46c6-b473-75ffc6d647d8.png)

2022-09-24 12:39 UTC, tufoinnkuo10 commented on js/index.js
> +const menu = document.getElementById('nav-items');
- [ optional] please note that on the desktop version, the mobile popup menu is not suppose to be visible. please consider fixing that
![Screenshot (468)](https://user-images.githubusercontent.com/65298048/192098416-9ec9464a-7fbf-4e48-8d45-e6191f75272a.png)

2022-11-03 07:40 UTC, merged